msg = input('Digite algo: ')
print('O tipo primitivo desse valor é', type(msg))
print('Só tem espaços? ', msg.isspace())
print('É numérico? ', msg.isnumeric())
print('É alfabetico? ', msg.isalpha())
print('É alfanumérico? ', msg.isalnum())
print('Está em maiusculo? ', msg.isupper())
print('Está em minusculo? ', msg.islower())
print('Está capitalizada? ', msg.istitle())