nome = str(input('\033[35mDigite seu nome completo: '))
print ('Seu nome em maiúsculas é',(nome.upper()))
print ('Seu nome em minúsculas é',(nome.lower()))
print (f'Seu nome tem ao todo tem {len(nome) - nome.count(' ')} letras')
print (f'Seu primeiro nome é {nome.split()[0]}')
print (f'Seu primeiro nome tem {len(nome.split()[0])} letras')