nome = str(input('Digite seu nome completo: '))
print('Seu nome em maiusculas é', nome.upper())
print('Seu nome em minusculas é', nome.lower())
print(f'Seu nome tem ao todo, {len(nome) - nome.count(' ')} letras')
print(f'Seu primeiro nome é {nome.split()[0]}')
print(f'Seu primeiro nome tem {len(nome.split()[0])} letras')